#!/bin/bash
set -e

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" <<-EOSQL
    CREATE DATABASE "Identities";
    CREATE DATABASE "Vehicles";
    CREATE DATABASE "Media";
    CREATE DATABASE "Notifications";
    CREATE DATABASE "Ais";
    GRANT ALL PRIVILEGES ON DATABASE "Identities" TO $POSTGRES_USER;
    GRANT ALL PRIVILEGES ON DATABASE "Vehicles" TO $POSTGRES_USER;
    GRANT ALL PRIVILEGES ON DATABASE "Media" TO $POSTGRES_USER;
    GRANT ALL PRIVILEGES ON DATABASE "Notifications" TO $POSTGRES_USER;
    GRANT ALL PRIVILEGES ON DATABASE "Ais" TO $POSTGRES_USER;
EOSQL
