// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Verendar.Vehicle.Infrastructure.Data;

#nullable disable

namespace Verendar.Vehicle.Infrastructure.Migrations
{
    [DbContext(typeof(VehicleDbContext))]
    [Migration("20260124112127_AddStatusToPartCategory")]
    partial class AddStatusToPartCategory
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Verendar.Vehicle.Domain.Entities.DefaultMaintenanceSchedule", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("uuid");

                    b.Property<int>("InitialKm")
                        .HasColumnType("integer");

                    b.Property<int>("KmInterval")
                        .HasColumnType("integer");

                    b.Property<int>("MonthsInterval")
                        .HasColumnType("integer");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<Guid>("PartCategoryId")
                        .HasColumnType("uuid");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid");

                    b.Property<Guid>("VehicleModelId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("PartCategoryId");

                    b.HasIndex("VehicleModelId", "PartCategoryId")
                        .IsUnique()
                        .HasFilter("\"DeletedAt\" IS NULL");

                    b.ToTable("DefaultMaintenanceSchedules");
                });

            modelBuilder.Entity("Verendar.Vehicle.Domain.Entities.MaintenanceRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("uuid");

                    b.Property<string>("GarageAddress")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("GarageName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("InvoiceImageUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Notes")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<int>("OdometerAtService")
                        .HasColumnType("integer");

                    b.Property<DateOnly>("ServiceDate")
                        .HasColumnType("date");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("TechnicianName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<decimal>("TotalCost")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UserVehicleId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserVehicleId", "ServiceDate")
                        .HasFilter("\"DeletedAt\" IS NULL");

                    b.ToTable("MaintenanceRecords");
                });

            modelBuilder.Entity("Verendar.Vehicle.Domain.Entities.MaintenanceRecordItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("uuid");

                    b.Property<string>("InstanceIdentifier")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<Guid>("MaintenanceRecordId")
                        .HasColumnType("uuid");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<Guid>("PartCategoryId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("PartProductId")
                        .HasColumnType("uuid");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.Property<decimal>("TotalPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid");

                    b.Property<bool>("UpdatesTracking")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("MaintenanceRecordId");

                    b.HasIndex("PartCategoryId");

                    b.HasIndex("PartProductId");

                    b.ToTable("MaintenanceRecordItems");
                });

            modelBuilder.Entity("Verendar.Vehicle.Domain.Entities.MaintenanceReminder", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<int>("CurrentOdometer")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("uuid");

                    b.Property<DateOnly?>("DismissedDate")
                        .HasColumnType("date");

                    b.Property<bool>("IsDismissed")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsNotified")
                        .HasColumnType("boolean");

                    b.Property<int>("Level")
                        .HasColumnType("integer");

                    b.Property<DateOnly?>("NotifiedDate")
                        .HasColumnType("date");

                    b.Property<decimal>("PercentageRemaining")
                        .HasColumnType("decimal(5,2)");

                    b.Property<DateOnly?>("TargetDate")
                        .HasColumnType("date");

                    b.Property<int>("TargetOdometer")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid");

                    b.Property<Guid>("VehiclePartTrackingId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("VehiclePartTrackingId", "Level")
                        .HasFilter("\"DeletedAt\" IS NULL");

                    b.ToTable("MaintenanceReminders");
                });

            modelBuilder.Entity("Verendar.Vehicle.Domain.Entities.OdometerHistory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("uuid");

                    b.Property<int>("OdometerValue")
                        .HasColumnType("integer");

                    b.Property<DateOnly>("RecordedDate")
                        .HasColumnType("date");

                    b.Property<int>("Source")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UserVehicleId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserVehicleId", "RecordedDate")
                        .HasFilter("\"DeletedAt\" IS NULL");

                    b.ToTable("OdometerHistories");
                });

            modelBuilder.Entity("Verendar.Vehicle.Domain.Entities.PartCategory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("AllowsMultipleInstances")
                        .HasColumnType("boolean");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("integer");

                    b.Property<string>("IconUrl")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<bool>("RequiresOdometerTracking")
                        .HasColumnType("boolean");

                    b.Property<bool>("RequiresTimeTracking")
                        .HasColumnType("boolean");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasFilter("\"DeletedAt\" IS NULL");

                    b.HasIndex("DisplayOrder", "Status")
                        .HasFilter("\"DeletedAt\" IS NULL");

                    b.ToTable("PartCategories");
                });

            modelBuilder.Entity("Verendar.Vehicle.Domain.Entities.PartProduct", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Brand")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid>("PartCategoryId")
                        .HasColumnType("uuid");

                    b.Property<string>("PriceCurrency")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<int?>("RecommendedKmInterval")
                        .HasColumnType("integer");

                    b.Property<int?>("RecommendedMonthsInterval")
                        .HasColumnType("integer");

                    b.Property<decimal?>("ReferencePrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("SKU")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Specifications")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("PartCategoryId", "Status")
                        .HasFilter("\"DeletedAt\" IS NULL");

                    b.ToTable("PartProducts");
                });

            modelBuilder.Entity("Verendar.Vehicle.Domain.Entities.UserVehicle", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int?>("AverageKmPerDay")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<int>("CurrentOdometer")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("uuid");

                    b.Property<string>("EngineNumber")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateOnly?>("LastOdometerUpdate")
                        .HasColumnType("date");

                    b.Property<string>("LicensePlate")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Notes")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<DateOnly?>("PurchaseDate")
                        .HasColumnType("date");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<string>("VIN")
                        .HasMaxLength(17)
                        .HasColumnType("character varying(17)");

                    b.Property<Guid>("VehicleVariantId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("VehicleVariantId");

                    b.HasIndex("UserId", "Status")
                        .HasFilter("\"DeletedAt\" IS NULL");

                    b.ToTable("UserVehicles");
                });

            modelBuilder.Entity("Verendar.Vehicle.Domain.Entities.VehicleBrand", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("uuid");

                    b.Property<string>("LogoUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("SupportPhone")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid");

                    b.Property<Guid>("VehicleTypeId")
                        .HasColumnType("uuid");

                    b.Property<string>("Website")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasFilter("\"DeletedAt\" IS NULL");

                    b.HasIndex("VehicleTypeId");

                    b.ToTable("VehicleBrands");
                });

            modelBuilder.Entity("Verendar.Vehicle.Domain.Entities.VehicleModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<decimal?>("EngineCapacity")
                        .HasColumnType("decimal(4,2)");

                    b.Property<int?>("EngineDisplacement")
                        .HasColumnType("integer");

                    b.Property<int?>("FuelType")
                        .HasColumnType("integer");

                    b.Property<int?>("ManufactureYear")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<int?>("TransmissionType")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid");

                    b.Property<Guid>("VehicleBrandId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasFilter("\"DeletedAt\" IS NULL");

                    b.HasIndex("VehicleBrandId", "Status")
                        .HasFilter("\"DeletedAt\" IS NULL");

                    b.ToTable("VehicleModels");
                });

            modelBuilder.Entity("Verendar.Vehicle.Domain.Entities.VehiclePartTracking", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("CurrentPartProductId")
                        .HasColumnType("uuid");

                    b.Property<int?>("CustomKmInterval")
                        .HasColumnType("integer");

                    b.Property<int?>("CustomMonthsInterval")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("uuid");

                    b.Property<string>("InstanceIdentifier")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<bool>("IsIgnored")
                        .HasColumnType("boolean");

                    b.Property<DateOnly?>("LastReplacementDate")
                        .HasColumnType("date");

                    b.Property<int?>("LastReplacementOdometer")
                        .HasColumnType("integer");

                    b.Property<string>("Notes")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<Guid>("PartCategoryId")
                        .HasColumnType("uuid");

                    b.Property<DateOnly?>("PredictedNextDate")
                        .HasColumnType("date");

                    b.Property<int?>("PredictedNextOdometer")
                        .HasColumnType("integer");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UserVehicleId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("CurrentPartProductId");

                    b.HasIndex("PartCategoryId");

                    b.HasIndex("UserVehicleId", "PartCategoryId", "InstanceIdentifier")
                        .IsUnique()
                        .HasFilter("\"DeletedAt\" IS NULL");

                    b.ToTable("VehiclePartTrackings");
                });

            modelBuilder.Entity("Verendar.Vehicle.Domain.Entities.VehicleType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasFilter("\"DeletedAt\" IS NULL");

                    b.ToTable("VehicleTypes");

                    b.HasData(
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111111"),
                            Code = "",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = new Guid("00000000-0000-0000-0000-000000000000"),
                            Description = "Xe máy hai bánh, bao gồm xe số, xe tay ga, xe côn tay",
                            Name = "Motorcycle",
                            Status = 1
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222222"),
                            Code = "",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = new Guid("00000000-0000-0000-0000-000000000000"),
                            Description = "Xe ô tô 4 bánh trở lên, bao gồm sedan, SUV, hatchback, MPV",
                            Name = "Car",
                            Status = 1
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-333333333333"),
                            Code = "",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = new Guid("00000000-0000-0000-0000-000000000000"),
                            Description = "Xe chạy bằng động cơ điện, bao gồm xe máy điện và ô tô điện",
                            Name = "Electric Vehicle",
                            Status = 1
                        });
                });

            modelBuilder.Entity("Verendar.Vehicle.Domain.Entities.VehicleTypeBrand", b =>
                {
                    b.Property<Guid>("VehicleTypeId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("VehicleBrandId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("uuid");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid");

                    b.HasKey("VehicleTypeId", "VehicleBrandId");

                    b.HasIndex("VehicleBrandId");

                    b.ToTable("VehicleTypeBrands");
                });

            modelBuilder.Entity("Verendar.Vehicle.Domain.Entities.VehicleVariant", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("uuid");

                    b.Property<string>("HexCode")
                        .IsRequired()
                        .HasMaxLength(7)
                        .HasColumnType("character varying(7)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid");

                    b.Property<Guid>("VehicleModelId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("VehicleModelId");

                    b.ToTable("VehicleVariants");
                });

            modelBuilder.Entity("Verendar.Vehicle.Domain.Entities.DefaultMaintenanceSchedule", b =>
                {
                    b.HasOne("Verendar.Vehicle.Domain.Entities.PartCategory", "PartCategory")
                        .WithMany("DefaultSchedules")
                        .HasForeignKey("PartCategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Verendar.Vehicle.Domain.Entities.VehicleModel", "VehicleModel")
                        .WithMany("DefaultSchedules")
                        .HasForeignKey("VehicleModelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PartCategory");

                    b.Navigation("VehicleModel");
                });

            modelBuilder.Entity("Verendar.Vehicle.Domain.Entities.MaintenanceRecord", b =>
                {
                    b.HasOne("Verendar.Vehicle.Domain.Entities.UserVehicle", "UserVehicle")
                        .WithMany("MaintenanceRecords")
                        .HasForeignKey("UserVehicleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("UserVehicle");
                });

            modelBuilder.Entity("Verendar.Vehicle.Domain.Entities.MaintenanceRecordItem", b =>
                {
                    b.HasOne("Verendar.Vehicle.Domain.Entities.MaintenanceRecord", "MaintenanceRecord")
                        .WithMany("Items")
                        .HasForeignKey("MaintenanceRecordId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Verendar.Vehicle.Domain.Entities.PartCategory", "PartCategory")
                        .WithMany("MaintenanceItems")
                        .HasForeignKey("PartCategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Verendar.Vehicle.Domain.Entities.PartProduct", "PartProduct")
                        .WithMany("MaintenanceItems")
                        .HasForeignKey("PartProductId");

                    b.Navigation("MaintenanceRecord");

                    b.Navigation("PartCategory");

                    b.Navigation("PartProduct");
                });

            modelBuilder.Entity("Verendar.Vehicle.Domain.Entities.MaintenanceReminder", b =>
                {
                    b.HasOne("Verendar.Vehicle.Domain.Entities.VehiclePartTracking", "PartTracking")
                        .WithMany("Reminders")
                        .HasForeignKey("VehiclePartTrackingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PartTracking");
                });

            modelBuilder.Entity("Verendar.Vehicle.Domain.Entities.OdometerHistory", b =>
                {
                    b.HasOne("Verendar.Vehicle.Domain.Entities.UserVehicle", "UserVehicle")
                        .WithMany("OdometerHistory")
                        .HasForeignKey("UserVehicleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("UserVehicle");
                });

            modelBuilder.Entity("Verendar.Vehicle.Domain.Entities.PartProduct", b =>
                {
                    b.HasOne("Verendar.Vehicle.Domain.Entities.PartCategory", "Category")
                        .WithMany("Products")
                        .HasForeignKey("PartCategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("Verendar.Vehicle.Domain.Entities.UserVehicle", b =>
                {
                    b.HasOne("Verendar.Vehicle.Domain.Entities.VehicleVariant", "Variant")
                        .WithMany()
                        .HasForeignKey("VehicleVariantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Variant");
                });

            modelBuilder.Entity("Verendar.Vehicle.Domain.Entities.VehicleBrand", b =>
                {
                    b.HasOne("Verendar.Vehicle.Domain.Entities.VehicleType", "VehicleType")
                        .WithMany("Brands")
                        .HasForeignKey("VehicleTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("VehicleType");
                });

            modelBuilder.Entity("Verendar.Vehicle.Domain.Entities.VehicleModel", b =>
                {
                    b.HasOne("Verendar.Vehicle.Domain.Entities.VehicleBrand", "Brand")
                        .WithMany("VehicleModels")
                        .HasForeignKey("VehicleBrandId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Brand");
                });

            modelBuilder.Entity("Verendar.Vehicle.Domain.Entities.VehiclePartTracking", b =>
                {
                    b.HasOne("Verendar.Vehicle.Domain.Entities.PartProduct", "CurrentPartProduct")
                        .WithMany("PartTrackings")
                        .HasForeignKey("CurrentPartProductId");

                    b.HasOne("Verendar.Vehicle.Domain.Entities.PartCategory", "PartCategory")
                        .WithMany("PartTrackings")
                        .HasForeignKey("PartCategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Verendar.Vehicle.Domain.Entities.UserVehicle", "UserVehicle")
                        .WithMany("PartTrackings")
                        .HasForeignKey("UserVehicleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CurrentPartProduct");

                    b.Navigation("PartCategory");

                    b.Navigation("UserVehicle");
                });

            modelBuilder.Entity("Verendar.Vehicle.Domain.Entities.VehicleTypeBrand", b =>
                {
                    b.HasOne("Verendar.Vehicle.Domain.Entities.VehicleBrand", "VehicleBrand")
                        .WithMany("VehicleTypeBrands")
                        .HasForeignKey("VehicleBrandId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Verendar.Vehicle.Domain.Entities.VehicleType", "VehicleType")
                        .WithMany("VehicleTypeBrands")
                        .HasForeignKey("VehicleTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("VehicleBrand");

                    b.Navigation("VehicleType");
                });

            modelBuilder.Entity("Verendar.Vehicle.Domain.Entities.VehicleVariant", b =>
                {
                    b.HasOne("Verendar.Vehicle.Domain.Entities.VehicleModel", "VehicleModel")
                        .WithMany("Variants")
                        .HasForeignKey("VehicleModelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("VehicleModel");
                });

            modelBuilder.Entity("Verendar.Vehicle.Domain.Entities.MaintenanceRecord", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("Verendar.Vehicle.Domain.Entities.PartCategory", b =>
                {
                    b.Navigation("DefaultSchedules");

                    b.Navigation("MaintenanceItems");

                    b.Navigation("PartTrackings");

                    b.Navigation("Products");
                });

            modelBuilder.Entity("Verendar.Vehicle.Domain.Entities.PartProduct", b =>
                {
                    b.Navigation("MaintenanceItems");

                    b.Navigation("PartTrackings");
                });

            modelBuilder.Entity("Verendar.Vehicle.Domain.Entities.UserVehicle", b =>
                {
                    b.Navigation("MaintenanceRecords");

                    b.Navigation("OdometerHistory");

                    b.Navigation("PartTrackings");
                });

            modelBuilder.Entity("Verendar.Vehicle.Domain.Entities.VehicleBrand", b =>
                {
                    b.Navigation("VehicleModels");

                    b.Navigation("VehicleTypeBrands");
                });

            modelBuilder.Entity("Verendar.Vehicle.Domain.Entities.VehicleModel", b =>
                {
                    b.Navigation("DefaultSchedules");

                    b.Navigation("Variants");
                });

            modelBuilder.Entity("Verendar.Vehicle.Domain.Entities.VehiclePartTracking", b =>
                {
                    b.Navigation("Reminders");
                });

            modelBuilder.Entity("Verendar.Vehicle.Domain.Entities.VehicleType", b =>
                {
                    b.Navigation("Brands");

                    b.Navigation("VehicleTypeBrands");
                });
#pragma warning restore 612, 618
        }
    }
}
