// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Verendar.Vehicle.Infrastructure.Data;

#nullable disable

namespace Verendar.Vehicle.Infrastructure.Migrations
{
    [DbContext(typeof(VehicleDbContext))]
    [Migration("20260210072134_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Verendar.Vehicle.Domain.Entities.DefaultMaintenanceSchedule", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("uuid");

                    b.Property<int>("InitialKm")
                        .HasColumnType("integer");

                    b.Property<int>("KmInterval")
                        .HasColumnType("integer");

                    b.Property<int>("MonthsInterval")
                        .HasColumnType("integer");

                    b.Property<Guid>("PartCategoryId")
                        .HasColumnType("uuid");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid");

                    b.Property<Guid>("VehicleModelId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("PartCategoryId");

                    b.HasIndex("VehicleModelId", "PartCategoryId")
                        .IsUnique()
                        .HasFilter("\"DeletedAt\" IS NULL");

                    b.ToTable("DefaultMaintenanceSchedules");

                    b.HasData(
                        new
                        {
                            Id = new Guid("d0000001-0000-0000-0000-000000000001"),
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = new Guid("00000000-0000-0000-0000-000000000000"),
                            InitialKm = 1000,
                            KmInterval = 3000,
                            MonthsInterval = 4,
                            PartCategoryId = new Guid("c0000001-0000-0000-0000-000000000001"),
                            Status = 1,
                            VehicleModelId = new Guid("a0000001-0000-0000-0000-000000000001")
                        },
                        new
                        {
                            Id = new Guid("d0000002-0000-0000-0000-000000000002"),
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = new Guid("00000000-0000-0000-0000-000000000000"),
                            InitialKm = 0,
                            KmInterval = 20000,
                            MonthsInterval = 36,
                            PartCategoryId = new Guid("c0000002-0000-0000-0000-000000000002"),
                            Status = 1,
                            VehicleModelId = new Guid("a0000001-0000-0000-0000-000000000001")
                        },
                        new
                        {
                            Id = new Guid("d0000003-0000-0000-0000-000000000003"),
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = new Guid("00000000-0000-0000-0000-000000000000"),
                            InitialKm = 0,
                            KmInterval = 0,
                            MonthsInterval = 24,
                            PartCategoryId = new Guid("c0000003-0000-0000-0000-000000000003"),
                            Status = 1,
                            VehicleModelId = new Guid("a0000001-0000-0000-0000-000000000001")
                        },
                        new
                        {
                            Id = new Guid("d0000004-0000-0000-0000-000000000004"),
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = new Guid("00000000-0000-0000-0000-000000000000"),
                            InitialKm = 0,
                            KmInterval = 10000,
                            MonthsInterval = 12,
                            PartCategoryId = new Guid("c0000004-0000-0000-0000-000000000004"),
                            Status = 1,
                            VehicleModelId = new Guid("a0000001-0000-0000-0000-000000000001")
                        },
                        new
                        {
                            Id = new Guid("d0000005-0000-0000-0000-000000000005"),
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = new Guid("00000000-0000-0000-0000-000000000000"),
                            InitialKm = 0,
                            KmInterval = 8000,
                            MonthsInterval = 12,
                            PartCategoryId = new Guid("c0000005-0000-0000-0000-000000000005"),
                            Status = 1,
                            VehicleModelId = new Guid("a0000001-0000-0000-0000-000000000001")
                        },
                        new
                        {
                            Id = new Guid("d0000006-0000-0000-0000-000000000006"),
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = new Guid("00000000-0000-0000-0000-000000000000"),
                            InitialKm = 0,
                            KmInterval = 6000,
                            MonthsInterval = 6,
                            PartCategoryId = new Guid("c0000006-0000-0000-0000-000000000006"),
                            Status = 1,
                            VehicleModelId = new Guid("a0000001-0000-0000-0000-000000000001")
                        },
                        new
                        {
                            Id = new Guid("d0000007-0000-0000-0000-000000000007"),
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = new Guid("00000000-0000-0000-0000-000000000000"),
                            InitialKm = 0,
                            KmInterval = 15000,
                            MonthsInterval = 0,
                            PartCategoryId = new Guid("c0000007-0000-0000-0000-000000000007"),
                            Status = 1,
                            VehicleModelId = new Guid("a0000001-0000-0000-0000-000000000001")
                        },
                        new
                        {
                            Id = new Guid("d0000008-0000-0000-0000-000000000008"),
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = new Guid("00000000-0000-0000-0000-000000000000"),
                            InitialKm = 0,
                            KmInterval = 20000,
                            MonthsInterval = 24,
                            PartCategoryId = new Guid("c0000008-0000-0000-0000-000000000008"),
                            Status = 1,
                            VehicleModelId = new Guid("a0000001-0000-0000-0000-000000000001")
                        },
                        new
                        {
                            Id = new Guid("d0000009-0000-0000-0000-000000000009"),
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = new Guid("00000000-0000-0000-0000-000000000000"),
                            InitialKm = 1000,
                            KmInterval = 3000,
                            MonthsInterval = 4,
                            PartCategoryId = new Guid("c0000009-0000-0000-0000-000000000009"),
                            Status = 1,
                            VehicleModelId = new Guid("a0000001-0000-0000-0000-000000000001")
                        },
                        new
                        {
                            Id = new Guid("d0000010-0000-0000-0000-000000000010"),
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = new Guid("00000000-0000-0000-0000-000000000000"),
                            InitialKm = 0,
                            KmInterval = 20000,
                            MonthsInterval = 24,
                            PartCategoryId = new Guid("c0000010-0000-0000-0000-000000000010"),
                            Status = 1,
                            VehicleModelId = new Guid("a0000001-0000-0000-0000-000000000001")
                        });
                });

            modelBuilder.Entity("Verendar.Vehicle.Domain.Entities.MaintenanceRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("uuid");

                    b.Property<string>("GarageName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("InvoiceImageUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Notes")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<int>("OdometerAtService")
                        .HasColumnType("integer");

                    b.Property<DateOnly>("ServiceDate")
                        .HasColumnType("date");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<decimal>("TotalCost")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UserVehicleId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserVehicleId", "ServiceDate")
                        .HasFilter("\"DeletedAt\" IS NULL");

                    b.ToTable("MaintenanceRecords");
                });

            modelBuilder.Entity("Verendar.Vehicle.Domain.Entities.MaintenanceRecordItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("uuid");

                    b.Property<string>("InstanceIdentifier")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<Guid>("MaintenanceRecordId")
                        .HasColumnType("uuid");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<Guid>("PartCategoryId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("PartProductId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid");

                    b.Property<bool>("UpdatesTracking")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("MaintenanceRecordId");

                    b.HasIndex("PartCategoryId");

                    b.HasIndex("PartProductId");

                    b.ToTable("MaintenanceRecordItems");
                });

            modelBuilder.Entity("Verendar.Vehicle.Domain.Entities.MaintenanceReminder", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<int>("CurrentOdometer")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("uuid");

                    b.Property<DateOnly?>("DismissedDate")
                        .HasColumnType("date");

                    b.Property<bool>("IsDismissed")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsNotified")
                        .HasColumnType("boolean");

                    b.Property<int>("Level")
                        .HasColumnType("integer");

                    b.Property<DateOnly?>("NotifiedDate")
                        .HasColumnType("date");

                    b.Property<decimal>("PercentageRemaining")
                        .HasColumnType("decimal(5,2)");

                    b.Property<DateOnly?>("TargetDate")
                        .HasColumnType("date");

                    b.Property<int>("TargetOdometer")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid");

                    b.Property<Guid>("VehiclePartTrackingId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("VehiclePartTrackingId", "Level")
                        .HasFilter("\"DeletedAt\" IS NULL");

                    b.ToTable("MaintenanceReminders");
                });

            modelBuilder.Entity("Verendar.Vehicle.Domain.Entities.OdometerHistory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("uuid");

                    b.Property<int?>("KmOnRecordedDate")
                        .HasColumnType("integer");

                    b.Property<int>("OdometerValue")
                        .HasColumnType("integer");

                    b.Property<DateOnly>("RecordedDate")
                        .HasColumnType("date");

                    b.Property<int>("Source")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UserVehicleId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserVehicleId", "RecordedDate")
                        .HasFilter("\"DeletedAt\" IS NULL");

                    b.ToTable("OdometerHistories");
                });

            modelBuilder.Entity("Verendar.Vehicle.Domain.Entities.PartCategory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("AllowsMultipleInstances")
                        .HasColumnType("boolean");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("ConsequencesIfNotHandled")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("integer");

                    b.Property<string>("IconUrl")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("IdentificationSigns")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<bool>("RequiresOdometerTracking")
                        .HasColumnType("boolean");

                    b.Property<bool>("RequiresTimeTracking")
                        .HasColumnType("boolean");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasFilter("\"DeletedAt\" IS NULL");

                    b.HasIndex("DisplayOrder", "Status")
                        .HasFilter("\"DeletedAt\" IS NULL");

                    b.ToTable("PartCategories");

                    b.HasData(
                        new
                        {
                            Id = new Guid("c0000001-0000-0000-0000-000000000001"),
                            AllowsMultipleInstances = false,
                            Code = "ENGINE-OIL",
                            ConsequencesIfNotHandled = "Mài mòn nhanh, kẹt piston; hỏng động cơ; chi phí sửa chữa rất cao hoặc phải thay máy.",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = new Guid("00000000-0000-0000-0000-000000000000"),
                            Description = "Dầu bôi trơn động cơ, cần thay định kỳ theo km hoặc thời gian",
                            DisplayOrder = 1,
                            IconUrl = "https://d3iova6424vljy.cloudfront.net/assets/OIP.webp",
                            IdentificationSigns = "Dầu đen, nhớt nhớt; động cơ nóng bất thường; đèn báo dầu sáng; tiếng kêu kim loại từ động cơ.",
                            Name = "Dầu nhớt động cơ",
                            RequiresOdometerTracking = true,
                            RequiresTimeTracking = true,
                            Status = 1
                        },
                        new
                        {
                            Id = new Guid("c0000002-0000-0000-0000-000000000002"),
                            AllowsMultipleInstances = true,
                            Code = "TIRE",
                            ConsequencesIfNotHandled = "Trượt, mất lái khi phanh/trời mưa; nổ lốp khi chạy tốc độ cao; tai nạn nghiêm trọng.",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = new Guid("00000000-0000-0000-0000-000000000000"),
                            Description = "Lốp trước và lốp sau, thay khi mòn hoặc đạt tuổi thọ",
                            DisplayOrder = 2,
                            IconUrl = "https://d3iova6424vljy.cloudfront.net/assets/OIP.webp",
                            IdentificationSigns = "Gai lốp mòn dưới 1.6mm; nứt rạn; phồng lốp; lốp non hơi thường xuyên; rung lái khi chạy.",
                            Name = "Lốp xe",
                            RequiresOdometerTracking = true,
                            RequiresTimeTracking = true,
                            Status = 1
                        },
                        new
                        {
                            Id = new Guid("c0000003-0000-0000-0000-000000000003"),
                            AllowsMultipleInstances = false,
                            Code = "BATTERY",
                            ConsequencesIfNotHandled = "Chết máy giữa đường; hỏng bình; ảnh hưởng bộ sạc và thiết bị điện; không khởi động được.",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = new Guid("00000000-0000-0000-0000-000000000000"),
                            Description = "Bình điện ắc quy, thay khi hết tuổi thọ hoặc không giữ điện",
                            DisplayOrder = 3,
                            IconUrl = "https://d3iova6424vljy.cloudfront.net/assets/OIP.webp",
                            IdentificationSigns = "Khởi động yếu hoặc không nổ; đèn pha mờ; ắc quy phồng, rỉ nước; xe để vài ngày là hết điện.",
                            Name = "Ắc quy",
                            RequiresOdometerTracking = false,
                            RequiresTimeTracking = true,
                            Status = 1
                        },
                        new
                        {
                            Id = new Guid("c0000004-0000-0000-0000-000000000004"),
                            AllowsMultipleInstances = true,
                            Code = "BRAKE-PAD",
                            ConsequencesIfNotHandled = "Mất phanh; đĩa phanh hỏng theo; va chạm, tai nạn do không dừng kịp.",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = new Guid("00000000-0000-0000-0000-000000000000"),
                            Description = "Má phanh trước và sau, thay khi mòn",
                            DisplayOrder = 4,
                            IconUrl = "https://d3iova6424vljy.cloudfront.net/assets/OIP.webp",
                            IdentificationSigns = "Tiếng kêu ken két khi phanh; phanh không ăn; tay phanh/ pedal bị trễ; đĩa phanh xước, rỗ.",
                            Name = "Má phanh",
                            RequiresOdometerTracking = true,
                            RequiresTimeTracking = true,
                            Status = 1
                        },
                        new
                        {
                            Id = new Guid("c0000005-0000-0000-0000-000000000005"),
                            AllowsMultipleInstances = false,
                            Code = "SPARK-PLUG",
                            ConsequencesIfNotHandled = "Chết máy; đánh lửa kém gây cháy không hết nhiên liệu, hỏng cat; hao xăng, giảm công suất.",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = new Guid("00000000-0000-0000-0000-000000000000"),
                            Description = "Bugi đánh lửa động cơ, thay định kỳ",
                            DisplayOrder = 5,
                            IconUrl = "https://d3iova6424vljy.cloudfront.net/assets/OIP.webp",
                            IdentificationSigns = "Khó nổ, giật khi tăng ga; tốn xăng; động cơ rung; bugi đen, dính dầu hoặc cháy trắng đầu điện cực.",
                            Name = "Bugi",
                            RequiresOdometerTracking = true,
                            RequiresTimeTracking = true,
                            Status = 1
                        },
                        new
                        {
                            Id = new Guid("c0000006-0000-0000-0000-000000000006"),
                            AllowsMultipleInstances = false,
                            Code = "AIR-FILTER",
                            ConsequencesIfNotHandled = "Bụi cát vào buồng đốt, mài mòn xy-lanh; giảm công suất; hỏng bugi, hao xăng lâu dài.",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = new Guid("00000000-0000-0000-0000-000000000000"),
                            Description = "Lọc không khí động cơ, cần vệ sinh và thay định kỳ",
                            DisplayOrder = 6,
                            IconUrl = "https://d3iova6424vljy.cloudfront.net/assets/OIP.webp",
                            IdentificationSigns = "Xe yếu, không bốc; tốn xăng; lọc gió bẩn, rách hoặc ẩm mốc; động cơ nổ không đều.",
                            Name = "Lọc gió",
                            RequiresOdometerTracking = true,
                            RequiresTimeTracking = true,
                            Status = 1
                        },
                        new
                        {
                            Id = new Guid("c0000007-0000-0000-0000-000000000007"),
                            AllowsMultipleInstances = false,
                            Code = "CHAIN-SPROCKET",
                            ConsequencesIfNotHandled = "Đứt xích khi chạy, bó bánh; hỏng nhông, moay-ơ; nguy cơ té xe, hỏng hộp số.",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = new Guid("00000000-0000-0000-0000-000000000000"),
                            Description = "Bộ truyền động xích và nhông, thay khi mòn",
                            DisplayOrder = 7,
                            IconUrl = "https://d3iova6424vljy.cloudfront.net/assets/OIP.webp",
                            IdentificationSigns = "Xích kêu lạch cạch; xích trùng dù đã chỉnh; răng nhông mòn vẹt; xích rỉ, khô dầu.",
                            Name = "Nhông sên dĩa",
                            RequiresOdometerTracking = true,
                            RequiresTimeTracking = false,
                            Status = 1
                        },
                        new
                        {
                            Id = new Guid("c0000008-0000-0000-0000-000000000008"),
                            AllowsMultipleInstances = false,
                            Code = "BRAKE-FLUID",
                            ConsequencesIfNotHandled = "Sôi dầu khi phanh gấp; mất phanh; hỏng xy-lanh phanh; tai nạn do không dừng kịp.",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = new Guid("00000000-0000-0000-0000-000000000000"),
                            Description = "Dầu phanh thủy lực, thay định kỳ theo thời gian hoặc km",
                            DisplayOrder = 8,
                            IconUrl = "https://d3iova6424vljy.cloudfront.net/assets/OIP.webp",
                            IdentificationSigns = "Dầu đổi màu đen hoặc vẩn đục; mức dầu thấp; phanh mềm hoặc trễ; có nước lẫn vào.",
                            Name = "Dầu phanh",
                            RequiresOdometerTracking = true,
                            RequiresTimeTracking = true,
                            Status = 1
                        },
                        new
                        {
                            Id = new Guid("c0000009-0000-0000-0000-000000000009"),
                            AllowsMultipleInstances = false,
                            Code = "OIL-FILTER",
                            ConsequencesIfNotHandled = "Dầu không lọc sạch, mài mòn động cơ; tắc lọc gây thiếu dầu; hỏng máy.",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = new Guid("00000000-0000-0000-0000-000000000000"),
                            Description = "Lọc dầu động cơ, thay kèm mỗi lần thay dầu nhớt",
                            DisplayOrder = 9,
                            IconUrl = "https://d3iova6424vljy.cloudfront.net/assets/OIP.webp",
                            IdentificationSigns = "Thay cùng chu kỳ dầu nhớt; lọc tắc khi đèn dầu sáng thường xuyên; dầu đen nhanh bất thường.",
                            Name = "Lọc dầu",
                            RequiresOdometerTracking = true,
                            RequiresTimeTracking = true,
                            Status = 1
                        },
                        new
                        {
                            Id = new Guid("c0000010-0000-0000-0000-000000000010"),
                            AllowsMultipleInstances = false,
                            Code = "COOLANT",
                            ConsequencesIfNotHandled = "Động cơ quá nhiệt; bó máy; hỏng gioăng, xy-lanh; chi phí sửa rất cao.",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = new Guid("00000000-0000-0000-0000-000000000000"),
                            Description = "Dung dịch làm mát động cơ, kiểm tra và thay định kỳ",
                            DisplayOrder = 10,
                            IconUrl = "https://d3iova6424vljy.cloudfront.net/assets/OIP.webp",
                            IdentificationSigns = "Mức nước trong bình thấp; nước đổi màu rỉ; động cơ nóng quá; rò rỉ dưới gầm.",
                            Name = "Nước làm mát",
                            RequiresOdometerTracking = true,
                            RequiresTimeTracking = true,
                            Status = 1
                        });
                });

            modelBuilder.Entity("Verendar.Vehicle.Domain.Entities.PartProduct", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Brand")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid>("PartCategoryId")
                        .HasColumnType("uuid");

                    b.Property<int?>("RecommendedKmInterval")
                        .HasColumnType("integer");

                    b.Property<int?>("RecommendedMonthsInterval")
                        .HasColumnType("integer");

                    b.Property<decimal?>("ReferencePrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("PartCategoryId", "Status")
                        .HasFilter("\"DeletedAt\" IS NULL");

                    b.ToTable("PartProducts");
                });

            modelBuilder.Entity("Verendar.Vehicle.Domain.Entities.UserVehicle", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int?>("AverageKmPerDay")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<int>("CurrentOdometer")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("uuid");

                    b.Property<DateOnly?>("LastOdometerUpdate")
                        .HasColumnType("date");

                    b.Property<string>("LicensePlate")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<bool>("NeedsOnboarding")
                        .HasColumnType("boolean");

                    b.Property<DateOnly?>("PurchaseDate")
                        .HasColumnType("date");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<string>("VIN")
                        .HasMaxLength(17)
                        .HasColumnType("character varying(17)");

                    b.Property<Guid>("VehicleVariantId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("VehicleVariantId");

                    b.HasIndex("UserId", "Status")
                        .HasFilter("\"DeletedAt\" IS NULL");

                    b.ToTable("UserVehicles");
                });

            modelBuilder.Entity("Verendar.Vehicle.Domain.Entities.VehicleBrand", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("uuid");

                    b.Property<string>("LogoUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("SupportPhone")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid");

                    b.Property<Guid>("VehicleTypeId")
                        .HasColumnType("uuid");

                    b.Property<string>("Website")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasFilter("\"DeletedAt\" IS NULL");

                    b.HasIndex("VehicleTypeId");

                    b.ToTable("VehicleBrands");

                    b.HasData(
                        new
                        {
                            Id = new Guid("b0000001-0000-0000-0000-000000000001"),
                            Code = "HONDA",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = new Guid("00000000-0000-0000-0000-000000000000"),
                            LogoUrl = "https://d3iova6424vljy.cloudfront.net/master/brands/0ea879b6-a573-4691-b00d-9f078f25b605.png",
                            Name = "Honda",
                            Status = 1,
                            SupportPhone = "18001076",
                            VehicleTypeId = new Guid("11111111-1111-1111-1111-111111111111"),
                            Website = "https://www.honda.com.vn"
                        },
                        new
                        {
                            Id = new Guid("b0000002-0000-0000-0000-000000000002"),
                            Code = "YAMAHA",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = new Guid("00000000-0000-0000-0000-000000000000"),
                            LogoUrl = "https://d3iova6424vljy.cloudfront.net/master/brands/0ea879b6-a573-4691-b00d-9f078f25b605.png",
                            Name = "Yamaha",
                            Status = 1,
                            SupportPhone = "18006019",
                            VehicleTypeId = new Guid("11111111-1111-1111-1111-111111111111"),
                            Website = "https://www.yamaha-motor.com.vn"
                        });
                });

            modelBuilder.Entity("Verendar.Vehicle.Domain.Entities.VehicleModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<decimal?>("EngineCapacity")
                        .HasColumnType("decimal(4,2)");

                    b.Property<int?>("EngineDisplacement")
                        .HasColumnType("integer");

                    b.Property<int?>("FuelType")
                        .HasColumnType("integer");

                    b.Property<int?>("ManufactureYear")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<int?>("TransmissionType")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid");

                    b.Property<Guid>("VehicleBrandId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasFilter("\"DeletedAt\" IS NULL");

                    b.HasIndex("VehicleBrandId", "Status")
                        .HasFilter("\"DeletedAt\" IS NULL");

                    b.ToTable("VehicleModels");

                    b.HasData(
                        new
                        {
                            Id = new Guid("a0000001-0000-0000-0000-000000000001"),
                            Code = "WAVE-ALPHA",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = new Guid("00000000-0000-0000-0000-000000000000"),
                            EngineCapacity = 1.10m,
                            EngineDisplacement = 110,
                            FuelType = 1,
                            ManufactureYear = 2020,
                            Name = "Wave Alpha",
                            Status = 1,
                            TransmissionType = 1,
                            VehicleBrandId = new Guid("b0000001-0000-0000-0000-000000000001")
                        },
                        new
                        {
                            Id = new Guid("a0000002-0000-0000-0000-000000000002"),
                            Code = "AIR-BLADE",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = new Guid("00000000-0000-0000-0000-000000000000"),
                            EngineCapacity = 1.25m,
                            EngineDisplacement = 125,
                            FuelType = 1,
                            ManufactureYear = 2021,
                            Name = "Air Blade",
                            Status = 1,
                            TransmissionType = 2,
                            VehicleBrandId = new Guid("b0000001-0000-0000-0000-000000000001")
                        },
                        new
                        {
                            Id = new Guid("a0000003-0000-0000-0000-000000000003"),
                            Code = "EXCITER",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = new Guid("00000000-0000-0000-0000-000000000000"),
                            EngineCapacity = 1.55m,
                            EngineDisplacement = 155,
                            FuelType = 1,
                            ManufactureYear = 2021,
                            Name = "Exciter",
                            Status = 1,
                            TransmissionType = 1,
                            VehicleBrandId = new Guid("b0000002-0000-0000-0000-000000000002")
                        },
                        new
                        {
                            Id = new Guid("a0000004-0000-0000-0000-000000000004"),
                            Code = "SIRIUS",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = new Guid("00000000-0000-0000-0000-000000000000"),
                            EngineCapacity = 1.10m,
                            EngineDisplacement = 110,
                            FuelType = 1,
                            ManufactureYear = 2020,
                            Name = "Sirius",
                            Status = 1,
                            TransmissionType = 1,
                            VehicleBrandId = new Guid("b0000002-0000-0000-0000-000000000002")
                        });
                });

            modelBuilder.Entity("Verendar.Vehicle.Domain.Entities.VehiclePartTracking", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("CurrentPartProductId")
                        .HasColumnType("uuid");

                    b.Property<int?>("CustomKmInterval")
                        .HasColumnType("integer");

                    b.Property<int?>("CustomMonthsInterval")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("uuid");

                    b.Property<string>("InstanceIdentifier")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<bool>("IsDeclared")
                        .HasColumnType("boolean");

                    b.Property<DateOnly?>("LastReplacementDate")
                        .HasColumnType("date");

                    b.Property<int?>("LastReplacementOdometer")
                        .HasColumnType("integer");

                    b.Property<Guid>("PartCategoryId")
                        .HasColumnType("uuid");

                    b.Property<DateOnly?>("PredictedNextDate")
                        .HasColumnType("date");

                    b.Property<int?>("PredictedNextOdometer")
                        .HasColumnType("integer");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UserVehicleId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("CurrentPartProductId");

                    b.HasIndex("PartCategoryId");

                    b.HasIndex("UserVehicleId", "PartCategoryId", "InstanceIdentifier")
                        .IsUnique()
                        .HasFilter("\"DeletedAt\" IS NULL");

                    b.ToTable("VehiclePartTrackings");
                });

            modelBuilder.Entity("Verendar.Vehicle.Domain.Entities.VehicleType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasFilter("\"DeletedAt\" IS NULL");

                    b.ToTable("VehicleTypes");

                    b.HasData(
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111111"),
                            Code = "MOTORCYCLE",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = new Guid("00000000-0000-0000-0000-000000000000"),
                            Description = "Xe máy hai bánh, bao gồm xe số, xe tay ga, xe côn tay",
                            ImageUrl = "https://d3iova6424vljy.cloudfront.net/assets/c51a1e61-9aac-4d59-a01c-5b615be9e794.jpg",
                            Name = "Xe máy",
                            Status = 1
                        });
                });

            modelBuilder.Entity("Verendar.Vehicle.Domain.Entities.VehicleVariant", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("uuid");

                    b.Property<string>("HexCode")
                        .IsRequired()
                        .HasMaxLength(7)
                        .HasColumnType("character varying(7)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid");

                    b.Property<Guid>("VehicleModelId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("VehicleModelId");

                    b.ToTable("VehicleVariants");

                    b.HasData(
                        new
                        {
                            Id = new Guid("e0000001-0000-0000-0000-000000000001"),
                            Color = "Đỏ đen",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = new Guid("00000000-0000-0000-0000-000000000000"),
                            HexCode = "#DC143C",
                            ImageUrl = "https://d3iova6424vljy.cloudfront.net/master/models/04c7786f-3546-4526-8fe4-6e3ff3196d18.png",
                            VehicleModelId = new Guid("a0000001-0000-0000-0000-000000000001")
                        },
                        new
                        {
                            Id = new Guid("e0000002-0000-0000-0000-000000000002"),
                            Color = "Đen bạc",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = new Guid("00000000-0000-0000-0000-000000000000"),
                            HexCode = "#000000",
                            ImageUrl = "https://d3iova6424vljy.cloudfront.net/master/models/04c7786f-3546-4526-8fe4-6e3ff3196d18.png",
                            VehicleModelId = new Guid("a0000001-0000-0000-0000-000000000001")
                        },
                        new
                        {
                            Id = new Guid("e0000003-0000-0000-0000-000000000003"),
                            Color = "Trắng ngọc trai",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = new Guid("00000000-0000-0000-0000-000000000000"),
                            HexCode = "#FFFFFF",
                            ImageUrl = "https://d3iova6424vljy.cloudfront.net/master/models/04c7786f-3546-4526-8fe4-6e3ff3196d18.png",
                            VehicleModelId = new Guid("a0000002-0000-0000-0000-000000000002")
                        },
                        new
                        {
                            Id = new Guid("e0000004-0000-0000-0000-000000000004"),
                            Color = "Xanh dương",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = new Guid("00000000-0000-0000-0000-000000000000"),
                            HexCode = "#4169E1",
                            ImageUrl = "https://d3iova6424vljy.cloudfront.net/master/models/04c7786f-3546-4526-8fe4-6e3ff3196d18.png",
                            VehicleModelId = new Guid("a0000002-0000-0000-0000-000000000002")
                        },
                        new
                        {
                            Id = new Guid("e0000005-0000-0000-0000-000000000005"),
                            Color = "Đen nhám",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = new Guid("00000000-0000-0000-0000-000000000000"),
                            HexCode = "#1C1C1C",
                            ImageUrl = "https://d3iova6424vljy.cloudfront.net/master/models/04c7786f-3546-4526-8fe4-6e3ff3196d18.png",
                            VehicleModelId = new Guid("a0000003-0000-0000-0000-000000000003")
                        },
                        new
                        {
                            Id = new Guid("e0000006-0000-0000-0000-000000000006"),
                            Color = "Đỏ GP",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = new Guid("00000000-0000-0000-0000-000000000000"),
                            HexCode = "#FF0000",
                            ImageUrl = "https://d3iova6424vljy.cloudfront.net/master/models/04c7786f-3546-4526-8fe4-6e3ff3196d18.png",
                            VehicleModelId = new Guid("a0000003-0000-0000-0000-000000000003")
                        },
                        new
                        {
                            Id = new Guid("e0000007-0000-0000-0000-000000000007"),
                            Color = "Xanh đen",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = new Guid("00000000-0000-0000-0000-000000000000"),
                            HexCode = "#000080",
                            ImageUrl = "https://d3iova6424vljy.cloudfront.net/master/models/04c7786f-3546-4526-8fe4-6e3ff3196d18.png",
                            VehicleModelId = new Guid("a0000004-0000-0000-0000-000000000004")
                        },
                        new
                        {
                            Id = new Guid("e0000008-0000-0000-0000-000000000008"),
                            Color = "Đen nhám",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = new Guid("00000000-0000-0000-0000-000000000000"),
                            HexCode = "#000000",
                            ImageUrl = "https://d3iova6424vljy.cloudfront.net/master/models/04c7786f-3546-4526-8fe4-6e3ff3196d18.png",
                            VehicleModelId = new Guid("a0000004-0000-0000-0000-000000000004")
                        });
                });

            modelBuilder.Entity("Verendar.Vehicle.Domain.Entities.DefaultMaintenanceSchedule", b =>
                {
                    b.HasOne("Verendar.Vehicle.Domain.Entities.PartCategory", "PartCategory")
                        .WithMany("DefaultSchedules")
                        .HasForeignKey("PartCategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Verendar.Vehicle.Domain.Entities.VehicleModel", "VehicleModel")
                        .WithMany("DefaultSchedules")
                        .HasForeignKey("VehicleModelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PartCategory");

                    b.Navigation("VehicleModel");
                });

            modelBuilder.Entity("Verendar.Vehicle.Domain.Entities.MaintenanceRecord", b =>
                {
                    b.HasOne("Verendar.Vehicle.Domain.Entities.UserVehicle", "UserVehicle")
                        .WithMany("MaintenanceRecords")
                        .HasForeignKey("UserVehicleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("UserVehicle");
                });

            modelBuilder.Entity("Verendar.Vehicle.Domain.Entities.MaintenanceRecordItem", b =>
                {
                    b.HasOne("Verendar.Vehicle.Domain.Entities.MaintenanceRecord", "MaintenanceRecord")
                        .WithMany("Items")
                        .HasForeignKey("MaintenanceRecordId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Verendar.Vehicle.Domain.Entities.PartCategory", "PartCategory")
                        .WithMany("MaintenanceItems")
                        .HasForeignKey("PartCategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Verendar.Vehicle.Domain.Entities.PartProduct", "PartProduct")
                        .WithMany("MaintenanceItems")
                        .HasForeignKey("PartProductId");

                    b.Navigation("MaintenanceRecord");

                    b.Navigation("PartCategory");

                    b.Navigation("PartProduct");
                });

            modelBuilder.Entity("Verendar.Vehicle.Domain.Entities.MaintenanceReminder", b =>
                {
                    b.HasOne("Verendar.Vehicle.Domain.Entities.VehiclePartTracking", "PartTracking")
                        .WithMany("Reminders")
                        .HasForeignKey("VehiclePartTrackingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PartTracking");
                });

            modelBuilder.Entity("Verendar.Vehicle.Domain.Entities.OdometerHistory", b =>
                {
                    b.HasOne("Verendar.Vehicle.Domain.Entities.UserVehicle", "UserVehicle")
                        .WithMany("OdometerHistory")
                        .HasForeignKey("UserVehicleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("UserVehicle");
                });

            modelBuilder.Entity("Verendar.Vehicle.Domain.Entities.PartProduct", b =>
                {
                    b.HasOne("Verendar.Vehicle.Domain.Entities.PartCategory", "Category")
                        .WithMany("Products")
                        .HasForeignKey("PartCategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("Verendar.Vehicle.Domain.Entities.UserVehicle", b =>
                {
                    b.HasOne("Verendar.Vehicle.Domain.Entities.VehicleVariant", "Variant")
                        .WithMany()
                        .HasForeignKey("VehicleVariantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Variant");
                });

            modelBuilder.Entity("Verendar.Vehicle.Domain.Entities.VehicleBrand", b =>
                {
                    b.HasOne("Verendar.Vehicle.Domain.Entities.VehicleType", "VehicleType")
                        .WithMany("Brands")
                        .HasForeignKey("VehicleTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("VehicleType");
                });

            modelBuilder.Entity("Verendar.Vehicle.Domain.Entities.VehicleModel", b =>
                {
                    b.HasOne("Verendar.Vehicle.Domain.Entities.VehicleBrand", "Brand")
                        .WithMany("VehicleModels")
                        .HasForeignKey("VehicleBrandId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Brand");
                });

            modelBuilder.Entity("Verendar.Vehicle.Domain.Entities.VehiclePartTracking", b =>
                {
                    b.HasOne("Verendar.Vehicle.Domain.Entities.PartProduct", "CurrentPartProduct")
                        .WithMany("PartTrackings")
                        .HasForeignKey("CurrentPartProductId");

                    b.HasOne("Verendar.Vehicle.Domain.Entities.PartCategory", "PartCategory")
                        .WithMany("PartTrackings")
                        .HasForeignKey("PartCategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Verendar.Vehicle.Domain.Entities.UserVehicle", "UserVehicle")
                        .WithMany("PartTrackings")
                        .HasForeignKey("UserVehicleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CurrentPartProduct");

                    b.Navigation("PartCategory");

                    b.Navigation("UserVehicle");
                });

            modelBuilder.Entity("Verendar.Vehicle.Domain.Entities.VehicleVariant", b =>
                {
                    b.HasOne("Verendar.Vehicle.Domain.Entities.VehicleModel", "VehicleModel")
                        .WithMany("Variants")
                        .HasForeignKey("VehicleModelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("VehicleModel");
                });

            modelBuilder.Entity("Verendar.Vehicle.Domain.Entities.MaintenanceRecord", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("Verendar.Vehicle.Domain.Entities.PartCategory", b =>
                {
                    b.Navigation("DefaultSchedules");

                    b.Navigation("MaintenanceItems");

                    b.Navigation("PartTrackings");

                    b.Navigation("Products");
                });

            modelBuilder.Entity("Verendar.Vehicle.Domain.Entities.PartProduct", b =>
                {
                    b.Navigation("MaintenanceItems");

                    b.Navigation("PartTrackings");
                });

            modelBuilder.Entity("Verendar.Vehicle.Domain.Entities.UserVehicle", b =>
                {
                    b.Navigation("MaintenanceRecords");

                    b.Navigation("OdometerHistory");

                    b.Navigation("PartTrackings");
                });

            modelBuilder.Entity("Verendar.Vehicle.Domain.Entities.VehicleBrand", b =>
                {
                    b.Navigation("VehicleModels");
                });

            modelBuilder.Entity("Verendar.Vehicle.Domain.Entities.VehicleModel", b =>
                {
                    b.Navigation("DefaultSchedules");

                    b.Navigation("Variants");
                });

            modelBuilder.Entity("Verendar.Vehicle.Domain.Entities.VehiclePartTracking", b =>
                {
                    b.Navigation("Reminders");
                });

            modelBuilder.Entity("Verendar.Vehicle.Domain.Entities.VehicleType", b =>
                {
                    b.Navigation("Brands");
                });
#pragma warning restore 612, 618
        }
    }
}
