global using Microsoft.EntityFrameworkCore;
global using Microsoft.EntityFrameworkCore.Metadata.Builders;
global using Verendar.Common.Databases.Base;
global using Verendar.Common.Databases.Implements;
global using Verendar.Common.Databases.UnitOfWork;
global using Verendar.Garage.Domain.Entities;
global using Verendar.Garage.Domain.Enums;
global using Verendar.Garage.Domain.Repositories.Interfaces;
global using Verendar.Garage.Infrastructure.Data;
